### ISSUE TITLE
Passing component to wrapper

### ISSUE THREAD

**Issue by michaek** [JAForbes/mithril-map-router#1]
What do you think of passing the entire component to the wrap function, rather than just its controller? That would allow us to use some other logic on the component (perhaps a `connect` member) in the visitor to determine what to pass to the RealController.

**Comment by JAForbes** [comment]
I like the idea of giving the user more control.  But I don't see the usage case.  Is the `connect` member a way to share state across components?

You can achieve that by just returning the object in the `visitor`

So...

``` js
var connect = {}

mapRoutes(() => connect, container, '/' ,{
  //...
})
```

That would then pass the connect hash to every route as a parameter, and they can share this persistent object, without it actually being global.

Which is what that `R.always(data)` example was illustrating (poorly) in the readme
This approach keeps the unidirectional data flow approach that makes mithril so useful.
Instead of attaching state, we are passing it to a controller function as an argument.

Does that cover your use case?  Or am I misunderstanding what `connect` is all about?

**Comment by michaek** [comment]
I was imagining the connect member as specifying how a component would connect to a data store like redux. I haven't thought it through all the way yet, but I was imagining something parallel to mapStateToProps and mapDispatchToProps in [react-redux](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options).

**Comment by michaek** [comment]
Also, I thought `R.always(data)` was a good example. :)

**Comment by JAForbes** [comment]
> Also, I thought R.always(data) was a good example. :)

Thanks!  :)

> I was imagining the connect member as specifying how a component would connect to a data store like redux.

I'm not very familiar with react or redux, so I completely missed you referencing it, sorry.

If there's some use case that you can illustrate that couldn't be achieved with the current functionality I'd be happy to add it.  I'd also like to keep it as simple as possible so there are not many suprises for those familiar with the mithril router.

But I imagine if you had some kind of module mimicking react's state management as a module, you could expose access to it using this function without any issues.

**Comment by michaek** [comment]
The part that I'm thinking about is that there can some logic about how to expose the store to the component. That logic could live within the visitor, and it may not need access to anything other than the route. If we wanted the logic to live with the component (something like the component saying "this is the part of the store I'm concerned with") that would require the visitor to know more than it currently has access to. Since it already has access to the component's controller, I was wondering if it would be useful for it to have access to the component, which would let us define the logic there.

If it's not a use case that's appealing, I'm happy to achieve this by [other means](https://github.com/bmartel/mithril-redux-starter-webpack/blob/master/src/utils/mithril-redux.js). :) Thanks!
